version: '2.2'

services:
  frontend:
    image: habit-front
    build: .
    ports:
      - "4000:4000"
    restart: on-failure
    container_name: habit-front
    volumes:
      - .:/app
      - /app/node_modules